### ISSUE TITLE
Backend checklist

### ISSUE THREAD

**Issue by mison201** [codelight-co/runebeta#15]
- [ ]  GET - User profile
- [ ]  POST - Login
- [ ]  POST - Logout

## GET - Block height
- [ ] Mock data form runealpha
- [ ] Get data from indexer

## GET - Daily transaction count
- [ ] Mock data form runealpha
- [ ] Write to database

## GET - List transaction
- [ ] Mock data form runealpha
- [ ] Query from database

## GET - Protocol Stats (Total Rune Etched, Total Rune Transaction, Total Fee, Daily Transaction)
- [ ] Mock data form runealpha
- [ ] Query from database

##  GET - Block sync number
- [ ] Mock data form runealpha
- [ ] Write to database
- [ ] Query from database

## GET - Search All (Transation id, rune id, block number...)
- [ ] Mock data form runealpha
- [ ] Query from database

## GET - Transaction by id
- [ ] Mock data form runealpha
- [ ] Query from database

## GET - List transaction by address
- [ ] Mock data form runealpha
- [ ] Query from database

##  GET - List rune
- [ ] Mock data form runealpha
- [ ] Query from database

## GET - Rune info by id
- [ ] Mock data form runealpha
- [ ] Query from database

## GET - Top rune holder
- [ ] Mock data form runealpha
- [ ] Query from database
- [ ] Write to database

## GET - List transaction by rune id
- [ ] Mock data form runealpha
- [ ] Query from database

 ## POST - Transfer rune to address
- [ ] Demo flow
- [ ] Api transfer

## POST Etching/Mint rune
- [ ] Demo flow
- [ ] Api Etching/Mint 

## GET - Market Stats
- [ ] Mock data form runealpha
- [ ] Collect and Write to database
- [ ] Query from database

## GET - List rune on market
- [ ] Mock data form runealpha
- [ ] Collect and Write to database
- [ ] Query from database

## POST - List rune to marketpalce
- [ ] Demo flow
- [ ] Create market structure
- [ ] Api get my UTXO
- [ ] Api create sell order
- [ ] Api buy order
